project_id = "trtrhiowukaetrptjsxo"

[functions.chat]
verify_jwt = false

[functions.verify]
verify_jwt = false

[functions.fetch-bulletins]
verify_jwt = false

[functions.get-bulletins]
verify_jwt = false
